# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.0005 --beta 0 --epoch 120 --trainname 'b7fd_decCond++Max' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0 --beta 1.0 --epoch 120 --trainname 'b7fd_decCond++TV' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'

python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.005 --beta 0 --epoch 120 --trainname 'b7fd_decCond++Max' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.05 --beta 0 --epoch 120 --trainname 'b7fd_decCond++Max' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.5 --beta 0 --epoch 120 --trainname 'b7fd_decCond++Max' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0 --beta 1.0 --epoch 120 --trainname 'b7fd_decCond++TV' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.0005 --beta 0.5 --epoch 120 --trainname 'b7fd_decCond++mix' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.0005 --beta 0.05 --epoch 120 --trainname 'b7fd_decCond++mix' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.0005 --beta 1.0 --epoch 120 --trainname 'b7fd_decCond++mix' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.005 --beta 1.0 --epoch 120 --trainname 'b7fd_decCond++mix' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.05 --beta 1.0 --epoch 120 --trainname 'b7fd_decCond++mix' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.05 --beta 0.01 --epoch 120 --trainname 'b7fd_decCond++mix' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'
# python NNtrain_arg.py --seed 77 --cuda 'cuda:1' --gama 0.05 --beta 0.05 --epoch 120 --trainname 'b7fd_decCond++mix' --lr 0.1 --folder 'fasttest' --batch 10 --rcsdir '/home/jiangxiaotian/datasets/traintest' --valdir '/home/jiangxiaotian/datasets/traintest'


